print("if we don't want to worry about a (expanding) vocabulary, feature hashing is a possibility, although it has some drawbacks.")
print("for instance, collisions mean our feature vector representations will be a little ambiguous (lossy)")
print("an up side is that we don't have to deal with a growing vocabulary length when new words are added")
print("it can also handle arbitrary size 'articles' or 'documents', or feature inputs more generally")


def feature_hash(size: int, article_or_feature: list[str]) -> list[int]:
    hash_table = [0] * size  # aka our feature vector

    for word in article_or_feature:
        hashed = hash(word)
        print("hashed value before mod it:", hashed)
        hashed = hashed % size
        print("hashed value after fitting it into our limited size vector:", hashed)
        hash_table[hashed] += 1

    print("our feature has representation of the article:", hash_table)
    return hash_table


article = [
            'Distribution', 'world', 'following', 'posted', 'doubt', 'retyped', 'Yigal', 'Ahrens',
            'importance', 'issue', 'almost', 'total', 'blackout', 'except', 'California', 'reposting',
            'appropriates', 'groups', 'From', 'Times', 'Friday', 'April', '1993', 'EVIDENCE',
            'SEIZED', 'POLICE', 'Richard', 'Paddock', 'Times', 'staff', 'writer', 'FRANCISCO',
            'Thursday', 'served', 'search', 'warrants', 'AntiDefamation', 'League', 'here', 'Angeles',
            'evidence', 'nationwide', 'intelligence', 'network', 'accused', 'keeping', 'files', 'more',
            'political', 'groups', 'newspapers', 'labor', 'unions', 'many', '12000', 'people',
            'operation', 'great', 'detail', 'Francisco', 'authorities', 'simultaneously', 'released', 'voluminous',
            'telling', 'operatives', 'AntiDefamation', 'League', 'searched', 'through', 'trash', 'infiltrated',
            'gather', 'intelligence', 'ArabAmerican', 'rightwing', 'what', 'they', 'called', 'pinko',
            'AntiDefamation', 'League', 'wellknown', 'organization', 'Jewish', 'community', 'dedicated', 'fighting',
            'declined', 'detailed', 'comment', 'Thursday', 'denied', 'breaking', 'laws', 'Police',
            'that', 'organization', 'maintains', 'undercover', 'operatives', 'gather', 'political', 'intelligence',
            'seven', 'cities', 'including', 'Angeles', 'Francisco', 'Groups', 'that', 'were',
            'operation', 'span', 'political', 'spectrum', 'including', 'such', 'groups', 'Klux',
            'White', 'Aryan', 'Resistance', 'Operation', 'Rescue', 'Greenpeace', 'National', 'Assn',
            'Colored', 'People', 'United', 'Farm', 'Workers', 'Jewish', 'Defense', 'League',
            'list', 'were', 'Mills', 'College', 'board', 'directors', 'Francisco', 'public',
            'station', 'KQED', 'Francisco', 'Guardian', 'newspaper', 'People', 'were', 'subjects',
            'included', 'former', 'Republican', 'Pete', 'McCloskey', 'jailed', 'political', 'extremist',
            'LaRouche', 'Angeles', 'Times', 'foreign', 'correspondent', 'Scott', 'Kraft', 'based',
            'Africa', 'Authorities', 'said', 'much', 'material', 'collected', 'groups', 'confidential',
            'obtained', 'illegally', 'from', 'enforcement', 'agencies', 'They', 'also', 'alleged',
            'data', 'some', 'individuals', 'organizations', 'sold', 'separately', 'South', 'African',
            'addition', 'allegations', 'obtaining', 'confidential', 'information', 'from', 'police', 'AntiDefamation',
            'could', 'face', 'total', 'felony', 'counts', 'properly', 'reporting', 'employment',
            'West', 'Coast', 'Bullock', 'according', 'affidavit', 'filed', 'justify', 'search',
            'AntiDefamation', 'League', 'disguised', 'payments', 'Bullock', 'more', 'than', 'years',
            'week', 'Beverly', 'Hills', 'attorney', 'Bruce', 'Hochman', 'then', 'paid',
            'according', 'documents', 'released', 'Francisco', 'Hochman', 'former', 'president', 'Jewish',
            'Council', 'Greater', 'Angeles', 'states', 'leading', 'attorneys', 'will', 'city',
            'late', 'next', 'week', 'could', 'reached', 'comment', 'office', 'said',
            '1990', 'Hochman', 'former', 'prosecutor', 'also', 'member', 'panel', 'appointed',
            'Pete', 'Wilson', 'secretly', 'make', 'initial', 'federal', 'judges', 'California',
            'former', 'regional', 'president', 'AntiDefamation', 'League', 'league', 'which', 'initially',
            'with', 'police', 'denied', 'repeatedly', 'that', 'operation', 'broke', 'laws',
            'officials', 'will', 'confirm', 'deny', 'whether', 'Bullock', 'employee', 'have',
            'they', 'simply', 'traded', 'information', 'with', 'police', 'departments', 'about',
            'might', 'involved', 'hate', 'crimes', 'affidavit', 'filed', 'obtain', 'warrants',
            'searches', 'Francisco', 'police', 'alleged', 'that', 'employees', 'were', 'apparently',
            'than', 'truthful', 'providing', 'information', 'during', 'earlier', 'search', 'conducted',
            'warrant', 'David', 'Lehrer', 'executive', 'director', 'Angeles', 'office', 'said',
            'violated', 'There', 'nothing', 'nefarious', 'about', 'operate', 'what', 'have',
            'said', 'record', 'speaks', 'itself', 'police', 'affidavit', 'contends', 'that',
            'sole', 'control', 'secret', 'fund', 'used', 'factfinding', 'operations', 'Lehrer',
            'documents', 'signed', 'checks', 'from', 'account', 'under', 'name', 'Patterson',
            'said', 'account', 'used', 'subscriptions', 'wide', 'variety', 'extremist', 'publications',
            'might', 'balk', 'sending', 'them', 'directly', 'AntiDefamation', 'League', 'Bullock',
            'collecting', 'intelligence', 'nearly', 'years', 'defended', 'efforts', 'during', 'lengthy',
            'with', 'Francisco', 'police', 'said', 'that', 'gathered', 'names', 'from',
            'sources', 'entered', 'them', 'into', 'computer', 'under', 'headings', 'such',
            'Pinkos', 'that', 'necessarily', 'mean', 'that', 'they', 'were', 'under',
            'might', 'never', 'call', 'them', 'again', 'Bullock', 'said', 'doesnt',
            'anything', 'that', 'theyre', 'files', 'threat', 'anyones', 'civil', 'rights',
            'name', 'appears', 'files', 'under', 'Pinko', 'recent', 'years', 'Bullock',
            'closely', 'with', 'Francisco', 'Police', 'Officer', 'Gerard', 'fled', 'Phillippines',
            'fall', 'after', 'questioned', 'case', 'former', 'employee', 'Gerard', 'supplied',
            'with', 'criminal', 'records', 'Department', 'Motor', 'Vehicles', 'information', 'such',
            'addresses', 'vehicle', 'registration', 'physical', 'drivers', 'license', 'photographs', 'Using',
            'gathered', 'AntiDefamation', 'League', 'Gerard', 'Bullock', 'also', 'provided', 'information',
            'African', 'government', 'receiving', '16000', 'over', 'four', 'years', 'documents',
            'file', 'Times', 'staff', 'writer', 'Kraft', 'which', 'apparently', 'sold',
            'African', 'government', 'provides', 'some', 'insight', 'into', 'hitandmiss', 'nature',
            'file', 'notes', 'that', 'Krafts', 'articles', 'appear', 'frequently', 'Times',
            'researched', 'written', 'little', 'else', 'about', 'file', 'accurate', 'brief',
            'confuses', 'Times', 'Kraft', 'with', 'another', 'Scott', 'Kraft', 'provides',
            'African', 'government', 'with', 'wrong', 'Krafts', 'physical', 'description', 'photograph',
            'personal', 'information', 'Nevertheless', 'documents', 'provide', 'illuminating', 'details', 'Bullock',
            'infiltrated', 'manner', 'organizations', 'from', 'skinheads', 'leftwing', 'radicals', 'searching',
            'through', 'trash', 'target', 'groups', 'Using', 'AntiDefamation', 'League', 'funds',
            'paid', 'informants', 'under', 'code', 'names', 'such', 'Scott', 'Scumbag',
            'closely', 'with', 'police', 'officers', 'down', 'coast', 'exchanged', 'information',
            'worked', 'with', 'federal', 'agencies', 'including', 'Bureau', 'Alcohol', 'Tobacco',
            'Bullocks', 'work', 'paid', 'informant', 'while', 'spying', 'behalf', 'AntiDefamation',
            'South', 'African', 'government', 'that', 'proved', 'undoing', 'learned', 'that',
            'foreign', 'government', 'began', 'investigating', 'leading', 'probe', 'AntiDefamation', 'Leagues',
            'network', 'AntiDefamation', 'League', 'employed', 'undercover', 'operatives', 'gather', 'information',
            'Francisco', 'York', 'Washington', 'Chicago', 'Louis', 'Atlanta', 'according', 'affidavit',
            'Joining', 'Francisco', 'police', 'searching', 'league', 'offices', 'Angeles', 'bank',
            'investigators', 'from', 'office', 'Francisco', 'Dist', 'Atty', 'Arlo', 'Smith',
            'Franchise', 'Board', 'Angeles', 'Police', 'Department', 'which', 'earlier', 'refused',
            'with', 'investigation', 'informed', 'searches', 'Angeles', 'invited', 'participate', 'Investigators',
            'that', 'some', 'confidential', 'information', 'AntiDefamation', 'League', 'files', 'have',
            'from', 'Angeles', 'police', 'officers', 'From', 'Angeles', 'Times', 'Saturday',
            '1993', 'VOWS', 'COOPERATE', 'WITH', 'INVESTIGATION', 'Richard', 'Paddock', 'Times',
            'writer', 'FRANCISCO', 'AntiDefamation', 'League', 'defended', 'record', 'civil', 'rights',
            'Friday', 'said', 'will', 'cooperate', 'with', 'authorities', 'investigating', 'whether',
            'collected', 'confidential', 'police', 'information', 'citizens', 'groups', 'Francisco', 'Dist',
            'Arlo', 'Smith', 'said', 'that', 'AntiDefamation', 'League', 'employees', 'involved',
            'gathering', 'could', 'face', 'many', 'felony', 'counts', 'receiving', 'confidential',
            'eavesdropping', 'violations', 'conspiracy', 'Police', 'have', 'accused', 'AntiDefamation', 'League',
            'truthful', 'about', 'spying', 'operations', 'which', 'collected', 'information', 'more',
            '12000', 'individuals', 'political', 'groups', 'across', 'political', 'spectrum', 'Hundreds',
            'documents', 'released', 'prosecutors', 'Thursday', 'show', 'that', 'maintained', 'nationwide',
            'network', 'kept', 'files', 'political', 'figures', 'Even', 'Smith', 'suggested',
            'AntiDefamation', 'League', 'shut', 'down', 'operation', 'prosecutors', 'would', 'take',
            'into', 'account', 'when', 'deciding', 'what', 'charges', 'file', 'statement',
            'Washington', 'National', 'Director', 'Abraham', 'Foxman', 'described', 'Jewish', 'defense',
            'which', 'fought', 'protect', 'minorities', 'from', 'bigotry', 'discrimination', 'years',
            'said', 'organization', 'regarded', 'credible', 'source', 'extremist', 'groups', 'tradition',
            'providing', 'information', 'police', 'journalists', 'academics', 'government', 'officials', 'public',
            'been', 'policy', 'obtain', 'information', 'illegally', 'said', 'Like', 'other',
            'order', 'protect', 'physical', 'safety', 'sources', 'will', 'comment', 'nature',
            'source', 'information', 'Foxman', 'said', 'AntiDefamation', 'League', 'refused', 'acknowledge',
            'longtime', 'employees', 'Bullock', 'anything', 'more', 'than', 'private', 'individual',
            'informant', 'Among', 'documents', 'released', 'prosecutors', 'were', 'detailed', 'statements',
            'funneled', 'weekly', 'payments', 'Bullock', 'through', 'Beverly', 'Hills', 'attorney',
            'Hochman', 'would', 'penetrate', 'organizations', 'needed', 'this', 'arrangement', 'distanced',
            'Hochman', 'told', 'Francisco', 'police', 'investigator', 'Hochman', 'could', 'reached',
            'home', 'office', 'comment', 'Despite', 'AntiDefamation', 'Leagues', 'assertion', 'that',
            'cooperate', 'with', 'authorities', 'Francisco', 'police', 'said', 'group', 'turn',
            'pertinent', 'documents', 'during', 'voluntary', 'search', 'groups', 'offices', 'Angeles',
            'last', 'fall', 'second', 'round', 'searches', 'Thursday', 'this', 'time',
            'search', 'warrants', 'produced', 'vast', 'quantity', 'records', 'primarily', 'dealing',
            'financial', 'transactions', 'Smith', 'said', 'Further', 'searches', 'necessary', 'will',
            'month', 'before', 'charges', 'filed', 'said', 'investigation', 'course', 'will',
            'facts', 'lead', 'district', 'attorney', 'said', 'Yigal', 'Arens', 'USCISI',
            'arensisiedu',
        ]

feature_hash(1024, article)
